name: server
version: 0.0.3-alpha
description: A simple websocket multiplexer for chat messages

dependencies:
  googleapis: any
  googleapis_auth: any
  http_server: any
  client:
   git:
       url: https://github.com/uni-im/client.git
       ref: 0.2.0
